package code;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Andryan
 */
public class formSupplier extends javax.swing.JPanel {

    clsSupplier objSupplier = new clsSupplier();
    private TableColumn column;
    
    public formSupplier() {
        initComponents();
        isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSupplier = new javax.swing.JTable();
        labelIdSupplier = new javax.swing.JLabel();
        txtIdSupplier = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        txtTelpSupplier = new javax.swing.JTextField();
        labelAlamat = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        txtAlamatSupplier = new javax.swing.JTextField();
        labelTelp = new javax.swing.JLabel();
        txtEmailSupplier = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 670));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));

        labelTitle.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        labelTitle.setText("Data Supplier");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(labelTitle)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(33, 33, 33))
        );

        add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(738, 250));

        tabelSupplier.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        tabelSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Supplier", "Nama Supplier", "Alamat", "Email", "No. Telp"
            }
        ));
        tabelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSupplier);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        labelIdSupplier.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        labelIdSupplier.setText("ID Supplier :");

        txtIdSupplier.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        txtIdSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdSupplierKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdSupplierKeyTyped(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        labelNama.setText("Nama Supplier :");

        txtTelpSupplier.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        txtTelpSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelpSupplierKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelpSupplierKeyTyped(evt);
            }
        });

        labelAlamat.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        labelAlamat.setText("Alamat :");

        txtNamaSupplier.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        txtNamaSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaSupplierKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaSupplierKeyTyped(evt);
            }
        });

        txtAlamatSupplier.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        txtAlamatSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatSupplierKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatSupplierKeyTyped(evt);
            }
        });

        labelTelp.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        labelTelp.setText("No. Telp");

        txtEmailSupplier.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        txtEmailSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailSupplierKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailSupplierKeyTyped(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        labelEmail.setText("Email :");

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAlamat)
                    .addComponent(labelIdSupplier))
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlamatSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTelp)
                .addGap(18, 18, 18)
                .addComponent(txtTelpSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNama))
                    .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelIdSupplier)
                        .addComponent(txtIdSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat)
                    .addComponent(txtAlamatSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addGap(27, 27, 27)
                .addGroup(panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelpSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelp))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(panelBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 430));

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));

        btnDelete.setBackground(new java.awt.Color(255, 102, 51));
        btnDelete.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-solid.png"))); // NOI18N
        btnDelete.setText(" DELETE");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus-solid.png"))); // NOI18N
        btnAdd.setText(" ADD");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(255, 255, 153));
        btnEdit.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pen-to-square-solid.png"))); // NOI18N
        btnEdit.setText(" EDIT");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        add(panelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 750, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSupplierKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if(((txtIdSupplier.getText().isEmpty())))
            {
                JOptionPane.showMessageDialog(this, "ID Supplier Tidak Boleh Kosong !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                txtIdSupplier.requestFocus();
            }
            else
            {
            } 
        }
    }//GEN-LAST:event_txtIdSupplierKeyPressed

    private void txtIdSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSupplierKeyTyped

    }//GEN-LAST:event_txtIdSupplierKeyTyped

    private void txtTelpSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpSupplierKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpSupplierKeyPressed

    private void txtTelpSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpSupplierKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpSupplierKeyTyped

    private void txtNamaSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaSupplierKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if(((txtNamaSupplier.getText().isEmpty())))
            {
                JOptionPane.showMessageDialog(this, "Nama Supplier Tidak Boleh Kosong !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                txtNamaSupplier.requestFocus();
            }
            else
            {
            } 
        }
    }//GEN-LAST:event_txtNamaSupplierKeyPressed

    private void txtNamaSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaSupplierKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSupplierKeyTyped

    private void txtAlamatSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatSupplierKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatSupplierKeyPressed

    private void txtAlamatSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatSupplierKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatSupplierKeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        objSupplier.Access();
        
        try{
            objSupplier.idSupplier = txtIdSupplier.getText();
        
            objSupplier.deleteSupplierData(objSupplier.idSupplier);
            try {
                objSupplier.res.executeUpdate(objSupplier.sql);
                objSupplier.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(formSupplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            cleanData();
            isiTabel();
        
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Proses penghapusan data gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        objSupplier.Access();
        
        if(txtIdSupplier.getText().equals(""))
        {
            JOptionPane.showMessageDialog( null, "ID Supplier Tidak Boleh Kosong!!!");
        } else {
            try{
                objSupplier.idSupplier = txtIdSupplier.getText();
                objSupplier.namaSupplier = txtNamaSupplier.getText();
                objSupplier.alamat = txtAlamatSupplier.getText();
                objSupplier.email = txtEmailSupplier.getText();
                objSupplier.telp = txtTelpSupplier.getText();
        
                objSupplier.saveSupplierData();
                try {
                    objSupplier.res.executeUpdate(objSupplier.sql);
                    objSupplier.conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(formSupplier.class.getName()).log(Level.SEVERE, null, ex);
                }
                cleanData();
                isiTabel();
        
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            } 
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Proses penyimpanan data gagal");
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        objSupplier.Access();
        
        try{
            objSupplier.idSupplier = txtIdSupplier.getText();
            objSupplier.namaSupplier = txtNamaSupplier.getText();
            objSupplier.alamat = txtAlamatSupplier.getText();
            objSupplier.email = txtEmailSupplier.getText();
            objSupplier.telp = txtTelpSupplier.getText();
        
            objSupplier.editSupplierData();
            try {
                objSupplier.res.executeUpdate(objSupplier.sql);
                objSupplier.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(formSupplier.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            cleanData();
            isiTabel();
        
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Proses pengeditan gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSupplierMouseClicked
        int baris = tabelSupplier.getSelectedRow();
        String id = tabelSupplier.getValueAt(baris, 0).toString();
        String nama = tabelSupplier.getValueAt(baris, 1).toString();
        String alamat = tabelSupplier.getValueAt(baris, 2).toString();
        String email = tabelSupplier.getValueAt(baris, 3).toString();
        String telp = tabelSupplier.getValueAt(baris, 4).toString();
        
        txtIdSupplier.setText(id);
        txtNamaSupplier.setText(nama);
        txtAlamatSupplier.setText(alamat);
        txtEmailSupplier.setText(email);
        txtTelpSupplier.setText(telp);
    }//GEN-LAST:event_tabelSupplierMouseClicked

    private void txtEmailSupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailSupplierKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailSupplierKeyPressed

    private void txtEmailSupplierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailSupplierKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailSupplierKeyTyped

    public void isiTabel(){
        DefaultTableModel tabelDataSupplier = new DefaultTableModel();
        
        tabelDataSupplier.addColumn("ID Supplier");
        tabelDataSupplier.addColumn("Nama Supplier");
        tabelDataSupplier.addColumn("Alamat");
        tabelDataSupplier.addColumn("Email");
        tabelDataSupplier.addColumn("No.Telp");
        
        try{
            objSupplier.Access();
            objSupplier.getSupplierData();
            
            Statement state = objSupplier.conn.createStatement();
            ResultSet result = state.executeQuery(objSupplier.sql);
            
            while(result.next()){
                tabelDataSupplier.addRow(new Object[] {result.getString(1),
                    result.getString(2), result.getString(3),
                    result.getString(4), result.getString(5)});
            }
            tabelSupplier.setModel(tabelDataSupplier);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Terjadi kesalahan pada penampilan data !!!");
            System.out.println(e.getMessage());
        }
    }
    
    public void cleanData()
    {
        txtIdSupplier.setText("");
        txtNamaSupplier.setText("");
        txtAlamatSupplier.setText("");
        txtEmailSupplier.setText("");
        txtTelpSupplier.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIdSupplier;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTelp;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTable tabelSupplier;
    private javax.swing.JTextField txtAlamatSupplier;
    private javax.swing.JTextField txtEmailSupplier;
    private javax.swing.JTextField txtIdSupplier;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtTelpSupplier;
    // End of variables declaration//GEN-END:variables
}
